query GetEventEntrants($slug: String!, $page: Int!, $perPage: Int) {
  event(slug: $slug) {
    entrants(query: { page: $page, perPage: $perPage }) {
      pageInfo {
        page
        perPage
        totalPages
      }
      nodes {
        name
        seeds {
          progressionSource {
            id
          }
          phaseGroup {
            displayIdentifier
            wave {
              identifier
            }
          }
          seedNum
        }
        skill
        participants {
          gamerTag
          prefix
          player {
            id
          }
        }
      }
    }
  }
}
